name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt update && sudo apt install -y clang cmake ninja-build

      - name: Install raylib dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            clang cmake ninja-build \
            libx11-dev libxcursor-dev libxrandr-dev \
            libxinerama-dev libxi-dev \
            libgl1-mesa-dev libasound2-dev

      - name: Build and install raylib
        run: |
          git clone --depth=1 https://github.com/raysan5/raylib.git
          cd raylib
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON
          cmake --build build
          sudo cmake --install build
      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-clang-build
          path: build/

